# Generated by Django 2.1.5 on 2019-01-23 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('full_name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('hobbies', models.CharField(max_length=200)),
                ('picture', models.CharField(max_length=200)),
                ('disorder', models.CharField(max_length=200)),
                ('solution', models.CharField(max_length=200)),
                ('risk_level', models.IntegerField()),
                ('icon', models.CharField(max_length=200)),
            ],
        ),
    ]
