# Generated by Django 2.1.5 on 2019-01-21 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('hobbies', models.TextField()),
                ('picture', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ChildDisorder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution', models.CharField(max_length=200)),
                ('risk_level', models.IntegerField()),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disorders', to='group.Child')),
            ],
        ),
        migrations.CreateModel(
            name='Disorder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('symptom', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='childdisorder',
            name='disorder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='group.Disorder'),
        ),
        migrations.AlterUniqueTogether(
            name='childdisorder',
            unique_together={('disorder', 'child')},
        ),
    ]
